[general]
import = [
"~/.config/alacritty/themes/themes/autumn.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
size = 14.0
normal = { family = "Hack Nerd Font", style = "Regular" }

